[phases.setup]
nixPkgs = [
    "espeak",
    "espeak-ng",
    "gcc",
    "pkg-config",
    "python311Full",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel"
]

[phases.install]
cmds = [
    "curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
    "python3.11 get-pip.py",
    "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.11 main.py" 