[phases.setup]
nixPkgs = [
    "espeak",
    "espeak-ng",
    "gcc",
    "pkg-config",
    "python39",
    "python39Packages.pip"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py" 