[phases.setup]
nixPkgs = [
    "espeak",
    "espeak-ng",
    "gcc",
    "pkg-config",
    "python311Full",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel"
]

[phases.install]
cmds = [
    "mkdir -p /opt/venv",
    "python3.11 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "python3.11 -m pip install --upgrade pip setuptools wheel",
    "python3.11 -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && exec python3.11 main.py" 